const root=document.documentElement,header=document.querySelector('header'),nav=document.querySelector('#siteNav'),menu=document.querySelector('#menuBtn'),theme=document.querySelector('#themeBtn'),links=[...document.querySelectorAll('nav a')];
const saved=localStorage.getItem('portfolio-theme');if(saved)root.dataset.theme=saved;
function icon(){theme.textContent=root.dataset.theme==='light'?'☾':'☼';theme.setAttribute('aria-label',root.dataset.theme==='light'?'Switch to dark theme':'Switch to light theme')}icon();
theme.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='light'?'dark':'light';localStorage.setItem('portfolio-theme',root.dataset.theme);icon()});
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});
links.forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>reveal.observe(e));
const sectionObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-40% 0px -50% 0px'});document.querySelectorAll('main section[id]').forEach(s=>sectionObs.observe(s));
addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>8),{passive:true});document.querySelector('#year').textContent=new Date().getFullYear();
const vmwareArchitecture=document.querySelector('img[src="assets/vmware-infrastructure-architecture.jpg"]');if(vmwareArchitecture)vmwareArchitecture.src='assets/vmware-infrastructure-architecture.png';
const factoryCard=[...document.querySelectorAll('.project')].find(card=>card.querySelector('h3')?.textContent.trim()==='Factory Network Redesign');if(factoryCard){factoryCard.querySelector('h3').textContent='Factory Network Redesign & Wi-Fi Upgrade';const summary=factoryCard.querySelector('p');if(summary)summary.textContent='Redesigned and rebuilt the aging factory network with an 8-core fiber backbone, four structured distribution points, dedicated PoE switching for wireless access points and IP phones, and separate data switching to support the Smart Factory initiative.';const tags=factoryCard.querySelector('.tags');if(tags)tags.innerHTML='<span>8-Core Fiber</span><span>PoE</span><span>Wi-Fi</span><span>Switching</span><span>Smart Factory</span>';if(!factoryCard.querySelector('a[href="factory-network.html"]')){const actions=document.createElement('div');actions.className='actions';actions.innerHTML='<a class="btn secondary" href="factory-network.html">View Project →</a>';factoryCard.appendChild(actions)}}